### ISSUE TITLE
Unicode wierdness

### ISSUE THREAD

**Issue by dreh23** [hybrid-publishing-lab/publishing-converter#7]
Output is not Unicode see:

```
<p class="Frontmatter">The Post-Media Lab is part of the LÃ¼neburg Innovation Incubator, a major EU project
     within Leuphana University of LÃ¼neburg, financed by the European Regional Development
     Fund and co-funded by the German federal state of </p>
```

$ uname -a
   Linux slim 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by gimsieke** [comment]
What’s the input like? You may create (and add, commit, push) a directory issues/7 in your local repo, put the source file into it and mention this issue #7 in the commit message. If the file contains sensitive information, you may put it into a private repo or send it via other means.

**Comment by gimsieke** [comment]
Oops, I forgot to commit a change to the html-generating code that inserts a `<meta charset="UTF-8"/>`. Please do a git pull & ext up.

**Comment by dreh23** [comment]
now it seems to work 

```
  <p class="Frontmatter">...Lüneburg .... </p>
```
